### ISSUE TITLE
Timer To-Do

### ISSUE THREAD

**Issue by LetsCode-Angus** [TheLetsCodeProject/ProjectOrbis_2#15]
Some additions that need to be made to the timer class.

**Check list:**
- [x] Default formatting options with constructor
- [x] static overload for format time which can have overridden formatting
- [x] A constructor for TimeData which can change formatting options

```C#
const string M_FORMATTING_PARAM = “00”;
const string S_FORMATTING_PARAM = “00.00”;
```
